wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.16.5
    framework: huggingface
    huggingface_version: 4.37.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1713946768.0
    t:
      1:
      - 1
      - 11
      - 12
      - 41
      - 45
      - 49
      - 55
      - 71
      - 83
      - 98
      3:
      - 4
      - 23
      - 42
      4: 3.10.14
      5: 0.16.5
      6: 4.37.2
      8:
      - 5
      13: linux-x86_64
