wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.5
    framework: huggingface
    huggingface_version: 4.37.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1723455638
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 71
      - 83
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 71
      - 83
      3:
      - 2
      - 4
      - 23
      - 42
      - 61
      4: 3.10.14
      5: 0.17.5
      6: 4.37.2
      8:
      - 5
      13: linux-x86_64
pretrained_teacher_model:
  desc: null
  value: /data/hepengyu/teachermodels/SD1-5
pretrained_vae_model_name_or_path:
  desc: null
  value: null
teacher_revision:
  desc: null
  value: null
revision:
  desc: null
  value: null
output_dir:
  desc: null
  value: /data/hepengyu/trainingLCM/output
cache_dir:
  desc: null
  value: /data/hepengyu/trainingLCM/cache
seed:
  desc: null
  value: 453645634
logging_dir:
  desc: null
  value: /data/hepengyu/trainingLCM/logs
report_to:
  desc: null
  value: wandb
checkpointing_steps:
  desc: null
  value: 1000
checkpoints_total_limit:
  desc: null
  value: 10
resume_from_checkpoint:
  desc: null
  value: latest
train_shards_path_or_url:
  desc: null
  value: pipe:curl -L -s file:///data/hepengyu/pictures/Laion-art-tar/{001..020}.tar
resolution:
  desc: null
  value: 512
interpolation_type:
  desc: null
  value: bilinear
center_crop:
  desc: null
  value: false
random_flip:
  desc: null
  value: false
dataloader_num_workers:
  desc: null
  value: 8
train_batch_size:
  desc: null
  value: 16
num_train_epochs:
  desc: null
  value: 9
max_train_steps:
  desc: null
  value: 5000
max_train_samples:
  desc: null
  value: 19234
learning_rate:
  desc: null
  value: 1.0e-06
scale_lr:
  desc: null
  value: false
lr_scheduler:
  desc: null
  value: constant
lr_warmup_steps:
  desc: null
  value: 500
gradient_accumulation_steps:
  desc: null
  value: 1
use_8bit_adam:
  desc: null
  value: true
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_weight_decay:
  desc: null
  value: 0.0
adam_epsilon:
  desc: null
  value: 1.0e-08
max_grad_norm:
  desc: null
  value: 1.0
proportion_empty_prompts:
  desc: null
  value: 0
w_min:
  desc: null
  value: 5.0
w_max:
  desc: null
  value: 15.0
num_ddim_timesteps:
  desc: null
  value: 50
loss_type:
  desc: null
  value: huber
huber_c:
  desc: null
  value: 0.001
unet_time_cond_proj_dim:
  desc: null
  value: 256
vae_encode_batch_size:
  desc: null
  value: 32
timestep_scaling_factor:
  desc: null
  value: 10.0
ema_decay:
  desc: null
  value: 0.95
mixed_precision:
  desc: null
  value: fp16
allow_tf32:
  desc: null
  value: false
cast_teacher_unet:
  desc: null
  value: false
enable_xformers_memory_efficient_attention:
  desc: null
  value: true
gradient_checkpointing:
  desc: null
  value: true
local_rank:
  desc: null
  value: 0
validation_steps:
  desc: null
  value: 200
push_to_hub:
  desc: null
  value: false
hub_token:
  desc: null
  value: null
hub_model_id:
  desc: null
  value: null
tracker_project_name:
  desc: null
  value: text2image-fine-tune
